// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/chainxx/bitx/internal/biz"
	"github.com/chainxx/bitx/internal/conf"
	"github.com/chainxx/bitx/internal/data"
	"github.com/chainxx/bitx/internal/task"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireApp(confData *conf.Data, binance *conf.Binance, logger log.Logger) (*app, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	marketDbRepo := data.NewMarketDataResource(dataData)
	tradesUseCase := biz.NewTradesUseCase(binance, marketDbRepo, logger)
	walletDbRepo := data.NewWalletDataSource(dataData)
	walletUseCase := biz.NewWalletUseCase(binance, walletDbRepo, logger)
	taskTask := task.NewTask(tradesUseCase, walletUseCase, binance, logger)
	mainApp := newApp(logger, taskTask)
	return mainApp, func() {
		cleanup()
	}, nil
}
