server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s

data:
  database:
    driver: mysql
    source: {user}:{passwd}@tcp(127.0.0.1:3306)/{db}
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

binance:
  apiKey: "{apiKey}"
  secretKey: "{secretKey}"
  symbols:
    - "BTCUSDT"
    - "BNBUSDT"
    - "ETHUSDT"
    - "EOSUSDT"
    - "OPUSDT"
    - "SHIBUSDT"
    - "PEOPLEUSDT"
    - "IDEXUSDT"
    - "FILUSDT"
    - "DOGEUSDT"
    - "LUNAUSDT"
