{
 "title": "bitx",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Symbol",
    "query": "select distinct(symbol) from ticker_price;"
   }
  ]
 },
 "panels": [
  {
   "title": "价格",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT open_time as time, open_price FROM bitx.ticker_price WHERE symbol = '${Symbol}' order by open_time;"
    },
    {
     "rawSql": "SELECT open_time as time, open_price FROM bitx.ticker_price WHERE symbol = '${Symbol}' order by open_time;"
    },
    {
     "rawSql": "SELECT open_time as time, low_price FROM bitx.ticker_price WHERE symbol = '${Symbol}' order by open_time;"
    },
    {
     "rawSql": "SELECT\n  open_time as time,\n  last_price\nFROM\n  bitx.ticker_price\nWHERE\n  symbol = '${Symbol}'\norder by\n  open_time;"
    },
    {
     "rawSql": "SELECT\n  open_time as time,\n  weighted_avg_price\nFROM\n  bitx.ticker_price\nWHERE\n  symbol = '${Symbol}'\norder by\n  open_time;"
    }
   ]
  },
  {
   "title": "成交量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT open_time as time, volume as '被买入和卖出的成交量' FROM bitx.ticker_price WHERE symbol = '${Symbol}' order by open_time;"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "交易价格",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT open_time as time, quote_volume as '多少个USDT的价值被交易' FROM bitx.ticker_price WHERE symbol = '${Symbol}' order by open_time;"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "单价价格变动",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT open_time as time, price_change FROM bitx.ticker_price WHERE symbol = '${Symbol}' order by open_time;"
    }
   ]
  },
  {
   "title": "价格变动百分比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "targets": [
    {
     "dataset": "bitx",
     "rawSql": "SELECT open_time as time, price_change_percent FROM bitx.ticker_price WHERE symbol = '${Symbol}' order by open_time;"
    }
   ]
  },
  {
   "title": "交易笔数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT open_time as time, `count` FROM bitx.ticker_price WHERE symbol = '${Symbol}' order by open_time;"
    }
   ]
  },
  {
   "title": "每日资产统计",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select \n  time as time, asset, free, locked \nFROM \n  bitx.daily_asset \nwhere \n  create_time > (unix_timestamp(now()) - 60 * 60 * 24)\norder by free desc;"
    }
   ]
  }
 ]
}